#ifndef KEYBOARD_H
#define KEYBOARD_H

#include <stdint.h>

enum key {
    KEY_NULL,
    KEY_UNKNOWN,

    KEY_ESC,
    KEY_1, KEY_2, KEY_3, KEY_4, KEY_5, KEY_6, KEY_7, KEY_8, KEY_9, KEY_0,
    KEY_MINUS, KEY_EQUAL, KEY_BACKSPACE,
    KEY_TAB,

    KEY_Q, KEY_W, KEY_E, KEY_R, KEY_T, KEY_Y, KEY_U, KEY_I, KEY_O, KEY_P,
    KEY_LEFTBRACKET, KEY_RIGHTBRACKET,
    KEY_ENTER,
    KEY_LEFTCTRL,

    KEY_A, KEY_S, KEY_D, KEY_F, KEY_G, KEY_H, KEY_J, KEY_K, KEY_L,
    KEY_SEMICOLON, KEY_APOSTROPHE, KEY_GRAVE,

    KEY_LEFTSHIFT, KEY_BACKSLASH,
    KEY_Z, KEY_X, KEY_C, KEY_V, KEY_B, KEY_N, KEY_M,
    KEY_COMMA, KEY_DOT, KEY_SLASH,
    KEY_RIGHTSHIFT,

    KEY_KP_ASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,

    KEY_F1, KEY_F2, KEY_F3, KEY_F4, KEY_F5, KEY_F6, KEY_F7, KEY_F8, KEY_F9, KEY_F10,
    KEY_NUMLOCK, KEY_SCROLLLOCK,

    KEY_HOME, KEY_UP, KEY_PGUP,
    KEY_LEFT, KEY_RIGHT,
    KEY_END, KEY_DOWN, KEY_PGDN,
    KEY_INSERT, KEY_DELETE,

    KEY_PRINTSCREEN,
    KEY_PAUSE,
    KEY_F11, KEY_F12
};

char key_ascii(uint8_t scancode);
uint8_t get_last_scancode();
enum key get_equ_key(uint8_t scancode);

#endif
