name: Format check

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    branches: [ main, master ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Clang-Format 22
        run: |
          sudo apt-get update
          sudo apt-get install -y wget software-properties-common gnupg
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 22
          sudo apt-get install -y clang-format-22
          sudo ln -sf /usr/bin/clang-format-22 /usr/bin/clang-format

      - name: Create config.mk for CI
        run: |
          cat > config.mk << 'EOF'
          ASM     := nasm
          CC      := i386-elf-gcc
          LD      := i386-elf-ld
          OBJCOPY := i386-elf-objcopy
          FLAGS   :=
          VMDISK  := 256
          VMRAM   := 128
          EOF

      - name: Check formatting
        run: |
          make format
          if ! git diff --exit-code; then
          echo "Files above are not formatted. Run 'make format' locally."
          exit 1
          fi
